add root metadata parsing
advancedtelematic/ota-plus-tools pull request #4
Opened 2017-08-29 16:03 UTC by taheris

Resolves [PRO-3889](https://advancedtelematic.atlassian.net/browse/PRO-3889).

2017-08-31 14:52 UTC, Danten commented on src/bin/ota_plus.rs
> +                .default_value("https://app.atsgarage.com")
Shouldn't this be something like `"https://tuf-reposerver.atsgarage.com"`?

2017-08-31 14:52 UTC, Danten commented on src/bin/ota_plus.rs
> +        .arg(arg_type())
Is it possible to get the keyid from this as well? Because I need that `keyid` when I'm adding a root key right?

2017-08-31 14:52 UTC, Danten commented on src/bin/ota_plus.rs
> +            SubCommand::with_name("add")
Hmm, maybe we should have a special command to add keys from the `keygen` command? because if it is generated by that command we don't need the `pem_file` field.

2017-09-04 09:11 UTC, heartsucker commented on src/bin/ota_plus.rs
> +            SubCommand::with_name("add")
@Danten Add keys to the DB on the server? What are you asking exactly?

2017-09-04 09:11 UTC, heartsucker commented on src/bin/ota_plus.rs
> +        .arg(arg_type())
@Danten What do you mean "get the keyid"? Print it to stdout?

2017-09-04 09:18 UTC, heartsucker requested changes

2017-09-04 09:18 UTC, heartsucker commented on src/bin/ota_plus.rs
> +            ("init", Some(sub)) => cmd_init(cache, sub),
I discovered this pattern while on vacation and face palmed at the abomination I'd written previously. :(

2017-09-04 09:18 UTC, heartsucker commented on src/bin/ota_plus.rs
> +    let mut file = File::open(s).map_err(|e| format!("error opening pem file: {}", e))?;
We should use `error_chain` for these to preserve the original error in its entirety.

2017-09-04 09:18 UTC, heartsucker commented on src/bin/ota_plus.rs
> +    s.parse::<u64>().map(|_| ()).map_err(|e| format!("invalid u64: {}", e))
`error_chain` again.

2017-09-04 09:18 UTC, heartsucker commented on src/cache.rs
> +        self.write_signed(self.metadata_path(Role::Root, true), signed, force)
DRY 😍

2017-09-04 09:18 UTC, heartsucker commented on src/tuf.rs
> +impl FromStr for Role {
This can be redone with a `#[serde(rename = "root")]`.

2017-09-04 09:18 UTC, heartsucker commented on src/tuf.rs
> +                    crypto::KeyType::Ed25519 => HEXLOWER.encode(&*public),
We don't use hexlower anymore. That nightmare of DER parsing/writing is to make the rust program place nice with the format expected by Bouncy Castle on the backend.

2017-09-04 09:18 UTC, heartsucker commented on src/tuf.rs
> +    public: String
I'm fairly sure this should be typed and not just `String`.

2017-09-04 09:19 UTC, heartsucker commented
In general the above review notes are reminders to myself for what to address since you probably won't see this until you're back from vacation.

2017-09-04 10:09 UTC, heartsucker commented on src/bin/ota_plus.rs
> +    let mut file = File::open(s).map_err(|e| format!("error opening pem file: {}", e))?;
Loljk, these are for the the validators for `clap`.

2017-09-05 09:49 UTC, heartsucker commented on src/bin/ota_plus.rs
> +        .arg(arg_type())
@Danten I'm merging this, so can you make another issue in PRO for this.

2017-09-05 09:49 UTC, heartsucker commented on src/bin/ota_plus.rs
> +            SubCommand::with_name("add")
@Danten I'm merging this, so can you make another issue in PRO for this.

2017-09-05 09:49 UTC, merged

2017-09-05 09:50 UTC, heartsucker commented
Closed by 1eaf100